### ISSUE TITLE
Table arrays containing primitive arrays unnecessarily serialize inline.

### ISSUE THREAD

**Issue by Evan-Walden-ATS** [xoofx/Tomlyn#72] opened 2023-10-02 19:54 UTC
The following TOML file:

```toml
[[table_array]]
primitive_list = [4, 5, 6]
```

When run through the functions Toml.ToModel & Toml.FromModel as follows:

```csharp

var toml = "[[table_array]]\nprimitive_list = [4, 5, 6]";

var model = Toml.ToModel(toml);
var tomlOut = Toml.FromModel(model);
```

Results in the following output:
```
table_array = [{primitive_list = [4, 5, 6]}]
```

I believe this may be a bug, as it appears that the serialization code otherwise prefers to use the non-inline style wherever possible.

**Comment by xoofx** [comment] 2023-11-23 06:48
I think that it's not really a bug but I have pushed a fix ffcc734 to mitigate it.

The problem is that TOML is not a roundtrip-able serialization format. There will be other cases like this.

If you need to be roundtrip-able, it would require to use only the Syntax tree but not the model tree (that doesn't know/store any information about the way things should be serialized back).

**Closed by xoofx** 2023-11-23 06:48 UTC
Labels: PR welcome
